import { ItemType } from '@/types/item'

export const SKILL_LIST: ItemType[] = [
  { text: 'React.js' },
  { text: 'Next.js' },
  { text: 'TypeScript' },
  { text: 'JavaScript' },
  { text: 'Ruby on Rails' },
  { text: 'Node.js' },
  { text: 'CSS | Sass/SCSS' },
  { text: 'Semantic HTML' },
  { text: 'SEO' },
  { text: 'Git' },
  { text: 'Figma' },
  { text: 'Responsive web design' },
  { text: 'Digital marketing tools integration' },
  { text: 'Web accessibility optimization' },
  { text: 'Teamwork' },
  { text: 'Proactivity' },
  { text: 'Continuous learning' },
  { text: 'Self-management skills' },
  { text: 'Attention to detail' },
  { text: 'Adaptability to change' },
  { text: 'Verbal communication' },
  { text: 'Analytical thinking' },
  { text: 'Autonomy in learning' },
  { text: 'Ability to give feedback' },
  { text: 'Written communication' },
  { text: 'Problem-solving skills' },
]
