export enum Page {
  HOME = 'HOME',
  ABOUT = 'ABOUT',
  ADDITIONAL_INFORMATION = 'ADDITIONAL_INFORMATION',
  CONTACT = 'CONTACT',
  SITE_UNDER_CONSTRUCTION = 'SITE_UNDER_CONSTRUCTION',
  SKILLS = 'SKILLS',
  WORK_EXPERIENCE = 'WORK_EXPERIENCE',
}
