name: Update Package Version

on:
  push:
    branches:
      - develop

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check for changes in package.json
        run: |
          # Fetch the previous commit hash if it exists
          PREV_COMMIT=$(git rev-parse HEAD^ || echo "")

          if [ -z "$PREV_COMMIT" ]; then
            echo "No previous commit found. Skipping version check."
            exit 0
          fi

          # Check for changes in package.json
          if git diff --name-only $PREV_COMMIT HEAD | grep -q package.json; then
            echo "Changes detected in package.json. Updating version..."
            npm version patch -m "Automatically updated version"
            git push origin develop --tags
          else
            echo "No changes detected in package.json."
          fi
