name: Update Package Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check for changes in package.json
        run: |
          git diff --name-only HEAD^ HEAD | grep package.json
          if [ $? -eq 0 ]; then
            echo "Changes detected in package.json. Updating version..."
            npm version patch -m "Automatically updated version"
            git push origin main --tags
          else
            echo "No changes detected in package.json."
          fi
